version: '3'

services:
  totara:
    build: ./docker/totara
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - ./siteroot:/var/www
  db:
    image: postgres:9.6
    restart: always
    environment:
      PHP_EXTENTION_XDEBUG: 1
      POSTGRES_PASSWORD: password
      POSTGRES_DB: totara
      POSTGRES_USER: totara
    volumes:
      - 'db:/var/lib/postgresql'
  test-db:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: moodle
      POSTGRES_USER: moodle_user
    volumes:
      - 'testdb:/var/lib/postgresql'
volumes:
    db:
    testdb: