version: '3'

services:
  totara:
    build: ./docker/totara
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - ./siteroot:/var/www
  db:
    image: postgres:9.6
    environment:
      PHP_EXTENTION_XDEBUG: 1
      POSTGRES_PASSWORD: password
      POSTGRES_DB: totara
      POSTGRES_USER: totara
    volumes:
      - 'db:/var/lib/postgresql'
  test-db:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: totara
      POSTGRES_USER: totara
    volumes:
      - 'testdb:/var/lib/postgresql'
  redis:
    image: redis
    restart: always
    volumes:
      - 'redis:/var/lib/redis'
  pgadmin:
    image: dpage/pgadmin4:4.18
    environment:
      PGADMIN_DEFAULT_EMAIL: moodle@moodle.com
      PGADMIN_DEFAULT_PASSWORD: moodle
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    links:
      - "db:pgadmin-server"
volumes:
    db:
    testdb:
    pgadmin:
    redis:
